include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    # Treat missing returns and dead code as errors.
    missing_return: error
    dead_code: error

linter:
  rules:
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - unawaited_futures
