import 'dart:io';

import 'package:oracle_core/oracle_core.dart';

/// Portable, Dart-native logical backup of the Oracle memory bank.
///
/// The dump is **data only** — the schema is owned by the migrations (the single
/// forward-only source of truth). A backup is a plain `.sql` file of `INSERT`
/// statements that restores into a freshly-migrated, empty schema. Because the
/// row literals are produced by Postgres itself (`quote_nullable(col::text)`),
/// every column type — `vector`, `text[]`, `jsonb`, `timestamptz`, `uuid` — is
/// encoded and escaped correctly with no per-type logic, and coerced back by the
/// column's input function on restore. Embeddings are included, so a restore
/// never needs to re-embed.
///
/// Why not `pg_dump`? Oracle runs both as a host-native binary (Windows) and in
/// the Linux container; a Dart dump needs no external tool on either, and the
/// resulting file is small, inspectable, and safe to commit — the memory bank
/// travels with the repo and restores identically anywhere.
class DbBackupService {
  final Database _db;
  const DbBackupService(this._db);

  /// Data tables in FK-dependency order: a table's referenced rows are always
  /// inserted before it. Rows within a table are ordered by `created_at` so a
  /// self-reference (`supersedes`) points at an already-inserted older row.
  /// The migration ledger (`_migrations`, `_migrations_lock`) is intentionally
  /// excluded — the schema/ledger is rebuilt by running migrations on restore.
  static const List<String> tables = [
    'organizations',
    'projects',
    'sessions',
    'requests',
    'architectures',
    'rules',
    'skills',
    'messages',
    'agent_events',
    'memories',
    'handoffs',
    'session_metrics',
  ];

  /// True when every data table is empty — the guard that keeps a restore from
  /// ever overwriting a populated memory bank.
  Future<bool> isEmpty() async {
    final expr = tables.map((t) => '(SELECT count(*) FROM $t)').join(' + ');
    final res = await _db.select(SqlStatement('SELECT $expr AS total', const {}));
    return (res.rows.first['total']?.toInt() ?? 0) == 0;
  }

  /// Total rows across all data tables.
  Future<int> _rowCount() async {
    final expr = tables.map((t) => '(SELECT count(*) FROM $t)').join(' + ');
    final res = await _db.select(SqlStatement('SELECT $expr AS total', const {}));
    return res.rows.first['total']?.toInt() ?? 0;
  }

  /// Writes a portable data seed to [path] (atomically: a temp file is written
  /// then renamed). Returns a summary. Parent directories are created.
  ///
  /// All row reads run in ONE `REPEATABLE READ` transaction, so the dump is a
  /// single consistent snapshot even while agents/hooks keep writing — without
  /// it, a row could arrive between two table reads and reference a parent the
  /// dump already passed, producing a seed that fails FK checks on restore.
  Future<DbBackupReport> backup(String path) async {
    // Column introspection can happen outside the snapshot: the schema is
    // static at runtime (migrations already ran).
    final columnsByTable = <String, List<String>>{
      for (final table in tables) table: await _tableColumns(table),
    };

    final results = await _db.executeSavePoint([
      // First statement of the transaction: upgrade it to a single snapshot.
      SavePointQuery(
          statement: const SqlStatement('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ', {})),
      for (final table in tables)
        SavePointQuery(statement: SqlStatement(_dumpSql(table, columnsByTable[table]!), const {})),
    ]);

    final buffer = StringBuffer()
      ..writeln('-- Oracle AI — portable data seed.')
      ..writeln('-- Restore into a freshly-migrated (empty) schema: the schema is')
      ..writeln('-- owned by the migrations; this file carries only rows (embeddings')
      ..writeln('-- included, so no re-embedding is needed).')
      ..writeln('-- Generated by DbBackupService. Do not edit by hand.')
      ..writeln();

    var totalRows = 0;
    final perTable = <String, int>{};
    for (var i = 0; i < tables.length; i++) {
      final table = tables[i];
      final rows = results[i + 1].rows; // results[0] is the SET statement
      perTable[table] = rows.length;
      totalRows += rows.length;
      buffer.writeln('-- $table (${rows.length} rows)');
      for (final row in rows) {
        buffer.writeln(row['stmt']!.toText()!);
      }
      buffer.writeln();
    }

    final file = File(path);
    await file.parent.create(recursive: true);
    final tmp = File('$path.tmp');
    await tmp.writeAsString(buffer.toString(), flush: true);
    if (await file.exists()) await file.delete();
    final written = await tmp.rename(path);

    return DbBackupReport(
      path: written.absolute.path,
      rows: totalRows,
      perTable: perTable,
      bytes: await written.length(),
    );
  }

  /// Restores [path] into the database. Non-destructive by default: skips unless
  /// the database is empty. Pass [force] to restore regardless (the caller is
  /// responsible for the data already there — restore does not truncate, so a
  /// forced restore into a populated DB will fail on primary-key conflicts).
  ///
  /// The whole file runs as one implicit transaction (simple query protocol), so
  /// a restore is all-or-nothing.
  Future<DbRestoreReport> restore(String path, {bool force = false}) async {
    final file = File(path);
    // Absolute in reports: relative inputs resolve against the *caller's* cwd
    // (a per-agent MCP runs in the agent's repo), so echoing them back is
    // ambiguous about where the file actually is.
    final abs = file.absolute.path;
    if (!await file.exists()) {
      return DbRestoreReport(path: abs, restored: false, rows: 0, reason: 'seed file not found');
    }
    if (!force && !await isEmpty()) {
      return DbRestoreReport(
          path: abs, restored: false, rows: 0, reason: 'database not empty (use force to override)');
    }
    final sql = await file.readAsString();
    if (sql.trim().isEmpty) {
      return DbRestoreReport(path: abs, restored: false, rows: 0, reason: 'seed file empty');
    }
    await _db.executeScript(sql);
    return DbRestoreReport(path: abs, restored: true, rows: await _rowCount(), reason: null);
  }

  /// Writable (non-generated) columns of [table], in ordinal order — a
  /// `GENERATED ALWAYS` column like `fts` cannot be written on restore.
  Future<List<String>> _tableColumns(String table) async {
    final res = await _db.select(SqlStatement(
      "SELECT column_name FROM information_schema.columns "
      "WHERE table_schema = 'public' AND table_name = :t AND is_generated = 'NEVER' "
      "ORDER BY ordinal_position",
      {'t': table},
    ));
    return res.rows.map((r) => r['column_name']!.toText()!).toList();
  }

  /// SQL that emits one `INSERT` statement per row of [table]. Each value is a
  /// Postgres-quoted literal of the column's text form (`quote_nullable`), which
  /// the target column's input function coerces back on restore — correct for
  /// every type (`vector`, `text[]`, `jsonb`, `uuid`, ...) with no per-type
  /// logic. Identifiers come from information_schema (the schema we own), never
  /// user input; double-quoted so reserved words like `key` are safe.
  String _dumpSql(String table, List<String> cols) {
    final colList = cols.map((c) => '"$c"').join(', ');
    final valueArgs = cols.map((c) => 'quote_nullable("$c"::text)').join(', ');
    return "SELECT 'INSERT INTO $table ($colList) VALUES (' || "
        "concat_ws(', ', $valueArgs) || ');' AS stmt "
        "FROM $table ORDER BY created_at, id";
  }
}

/// Summary of a [DbBackupService.backup].
class DbBackupReport {
  final String path;
  final int rows;
  final Map<String, int> perTable;
  final int bytes;
  const DbBackupReport({
    required this.path,
    required this.rows,
    required this.perTable,
    required this.bytes,
  });
}

/// Summary of a [DbBackupService.restore].
class DbRestoreReport {
  final String path;
  final bool restored;
  final int rows;

  /// Why the restore was skipped (null when [restored] is true).
  final String? reason;
  const DbRestoreReport({
    required this.path,
    required this.restored,
    required this.rows,
    required this.reason,
  });
}
